open-weather:
  apiKey: [ INSERT API KEY HERE ]
  uri: https://api.openweathermap.org/data/2.5/weather

nytimes:
  apiKey: ct2Am6KgzqW83GH8vLKSv0dKYAYV7lor
  uri: https://api.nytimes.com/svc/topstories/v2/

server:
  port: 8080